# MPI-based makefile using mpic++ and mpicc

INC_DIR =	/home/ckim/LIBs/mrmpi-7Apr14/src 
MR_LIB =	/home/ckim/LIBs/mrmpi-7Apr14/src/libmrmpi_mpicc.a
CC =		mpicc 
CPP =		mpic++ 
CCFLAGS =	-m64 -g -O3 -Wno-long-long -Wno-deprecated -I$(INC_DIR) 
LINK =		mpic++
LINKFLAGS =	-m64 -g -O3 -Wno-long-long -Wno-deprecated  
USRLIB =	$(MR_LIB)	
SYSLIB =

include Makefile.common
