# Targets

OBJS = mr_inchworm.o Fasta_reader.o sequenceUtil.o stacktrace.o Fasta_entry.o string_util.o mrSubroutine.o IRKE.o KmerCounter.o argProcessor.o

EXECUTABLE = mr_inchworm

all:	mr_inchworm

mr_inchworm:	$(OBJS) $(USRLIB)
	$(LINK) $(LINKFLAGS) $(OBJS) $(USRLIB) $(SYSLIB) -o $(EXECUTABLE) 

clean:
	rm $(OBJS) $(EXECUTABLE)

clean_obj:
	rm $(OBJS) 

# Rules

%.o:%.cpp
	$(CPP) $(CCFLAGS) -c $<

%.o:%.c
	$(CC) $(CCFLAGS) -c $<
