# Targets

OBJS = out_clustered_kmers.o Fasta_reader.o sequenceUtil.o stacktrace.o Fasta_entry.o string_util.o mrSubroutine.o IRKE.o KmerCounter.o argProcessor.o

EXECUTABLE =out_clustered_kmers 

all:	out_clustered_kmers	

out_clustered_kmers:	$(OBJS) $(USRLIB)
	$(LINK) $(LINKFLAGS) $(OBJS) $(USRLIB) $(SYSLIB) -o $(EXECUTABLE) 

clean:
	rm $(OBJS) $(EXECUTABLE)

clean_obj:
	rm $(OBJS) 

# Rules

%.o:%.cpp
	$(CPP) $(CCFLAGS) -c $<

%.o:%.c
	$(CC) $(CCFLAGS) -c $<
